### ISSUE TITLE
Can you explain

### ISSUE THREAD

**Issue by AleksCee** [driagi/node-red-contrib-alexa-remote2#1]
Hi,

nice flow - but can you explain what did the topic "A" does and what flow.alexa (seams to be empty on start?).
I like to understand what your really cool stuff does.... Can you explain the single nodes and there function?

Thanks, Alex

**Comment by stefanobertini** [comment]
Hi @AleksCee, 
IMHO the "topic" assignment is not used, maybe it's just for debugging purposes.
It is "A" if the actiton is started by a timer and "" on init.

No ideas about the flow.alexa.

**Comment by driagi** [comment]
@AleksCee Excuse me. I had shared my draft because it was requested (it worked anyway), but I had never checked the issues. I reposted the cleaned up flow
